# Generated by Django 5.1.4 on 2025-01-28 21:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("present", "0011_alter_product_age_range_alter_product_gender"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("views_count", models.PositiveIntegerField(default=0)),
                ("favorites_count", models.PositiveIntegerField(default=0)),
                ("purchases_count", models.PositiveIntegerField(default=0)),
                (
                    "last_updated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="present.product",
                    ),
                ),
            ],
        ),
    ]
