# Generated by Django 5.1.4 on 2025-01-26 01:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Recipients",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("100-1500", "100-1500 руб."),
                            ("1501-5000", "1501-5000 руб."),
                            ("5001-10000", "5001-10000 руб."),
                            ("10001-50000", "10001-50000 руб."),
                            ("50001-100000", "50001-100000 руб."),
                            ("100001-200000", "100001-200000 руб."),
                        ],
                        help_text="Желаемый диапазон цен для подарка",
                        max_length=25,
                        null=True,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("birthday", "День рождения"),
                            ("anniversary", "Юбилей"),
                            ("wedding", "Свадьба"),
                            ("new_year", "Новый год"),
                            ("women_day", "8 марта"),
                            ("other", "Другое"),
                        ],
                        default="birthday",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "relationship",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("mother", "Мама/Папа"),
                            ("wife", "Жена/Муж"),
                            ("daughter", "Дочь/Сын"),
                            ("sister", "Сестра/Брат"),
                            ("grandmother", "Бабушка/Дедушка"),
                            ("friend", "Подруга/Друг"),
                            ("other", "Другое"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "Мужчина"), ("female", "Женщина")],
                        default="male",
                        max_length=10,
                    ),
                ),
                (
                    "age_range",
                    models.CharField(
                        choices=[
                            (0, "0-1"),
                            (2, "2-6"),
                            (7, "7-13"),
                            (14, "14-25"),
                            (26, "26-50"),
                            (51, "51-70"),
                            (71, "71-120"),
                        ],
                        default=14,
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipients",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
