# Generated by Django 5.1.4 on 2025-01-27 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipients", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipients",
            old_name="price",
            new_name="price_range",
        ),
    ]
