# Generated by Django 5.1.4 on 2025-02-02 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipients", "0002_rename_price_recipients_price_range"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipients",
            name="event_type",
        ),
        migrations.RemoveField(
            model_name="recipients",
            name="relationship",
        ),
    ]
