# Generated by Django 5.1.4 on 2025-01-15 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipients", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipients",
            name="price_range",
            field=models.CharField(
                blank=True,
                choices=[
                    ("low", "До 20$"),
                    ("medium", "20$ - 50$"),
                    ("high", "50$ - 100$"),
                    ("premium", "Более 100$"),
                ],
                help_text="Желаемый диапазон цен для подарка",
                max_length=10,
                null=True,
            ),
        ),
    ]
