# Generated by Django 5.1.4 on 2025-01-24 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipients", "0004_alter_recipients_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipients",
            name="event_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("birthday", "День рождения"),
                    ("anniversary", "Юбилей"),
                    ("wedding", "Свадьба"),
                    ("new_year", "Новый год"),
                    ("women_day", "8 марта"),
                    ("other", "Другое"),
                ],
                default="birthday",
                max_length=20,
                null=True,
            ),
        ),
    ]
