# Generated by Django 5.1.4 on 2025-01-24 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipients", "0005_alter_recipients_event_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipients",
            old_name="price_range",
            new_name="price",
        ),
    ]
