# Generated by Django 5.1.4 on 2025-01-15 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("present", "0002_remove_category_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="currency",
            field=models.CharField(
                choices=[
                    ("USD", "US Dollar ($)"),
                    ("EUR", "Euro (€)"),
                    ("RUB", "Russian Ruble (₽)"),
                ],
                default="USD",
                max_length=3,
            ),
        ),
    ]
