# Generated by Django 5.1.4 on 2025-01-15 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("present", "0003_product_currency"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["name"]},
        ),
    ]
