# Generated by Django 5.1.4 on 2025-01-23 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("present", "0004_alter_category_options_alter_product_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="age_range",
            field=models.CharField(
                blank=True,
                choices=[
                    (0, "0-1"),
                    (2, "2-6"),
                    (7, "7-13"),
                    (14, "14-25"),
                    (26, "26-50"),
                    (51, "51-70"),
                    (71, "71-120"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="event_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("birthday", "День рождения"),
                    ("anniversary", "Юбилей"),
                    ("wedding", "Свадьба"),
                    ("new_year", "Новый год"),
                    ("women_day", "8 марта"),
                    ("other", "Другое"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="gender",
            field=models.CharField(
                choices=[
                    ("male", "Мужчина"),
                    ("female", "Женщина"),
                    ("unisex", "Унисекс"),
                ],
                default="unisex",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="relationship",
            field=models.CharField(
                blank=True,
                choices=[
                    ("mother", "Мама"),
                    ("father", "Папа"),
                    ("wife", "Жена"),
                    ("husband", "Муж"),
                    ("son", "Сын"),
                    ("daughter", "Дочь"),
                    ("brother", "Брат"),
                    ("sister", "Сестра"),
                    ("grandmother", "Бабушка"),
                    ("grandfather", "Дедушка"),
                    ("friend", "Друг"),
                    ("colleague", "Коллега"),
                    ("teacher", "Учитель"),
                    ("other", "Другое"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="currency",
            field=models.CharField(
                choices=[("USD", "$"), ("EUR", "€"), ("RUB", "₽")],
                default="USD",
                max_length=3,
            ),
        ),
    ]
