# Generated by Django 5.1.4 on 2025-01-25 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "present",
            "0005_product_age_range_product_event_type_product_gender_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="currency",
            field=models.CharField(
                choices=[("USD", "$"), ("EUR", "€"), ("RUB", "₽")],
                default="RUB",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="gender",
            field=models.CharField(
                choices=[("male", "Мужчина"), ("female", "Женщина")],
                default="male",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                blank=True,
                choices=[
                    ("100-1500", "100-1500 руб."),
                    ("1501-5000", "1501-5000 руб."),
                    ("5001-10000", "5001-10000 руб."),
                    ("10001-50000", "10001-50000 руб."),
                    ("50001-100000", "50001-100000 руб."),
                    ("100001-200000", "100001-200000 руб."),
                ],
                decimal_places=2,
                max_digits=10,
                null=True,
            ),
        ),
    ]
