# Generated by Django 5.1.4 on 2025-01-25 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("present", "0006_alter_product_currency_alter_product_gender_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
