# Generated by Django 5.1.4 on 2025-01-25 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("present", "0008_alter_product_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
    ]
