# Generated by Django 5.1.4 on 2025-01-26 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("present", "0009_alter_product_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="price_range",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
