# Generated by Django 5.1.4 on 2025-01-26 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("present", "0010_product_price_range"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="age_range",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="product",
            name="gender",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
