# Generated by Django 5.1.4 on 2025-02-02 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("present", "0011_alter_product_age_range_alter_product_gender"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="event_type",
        ),
        migrations.RemoveField(
            model_name="product",
            name="relationship",
        ),
    ]
